### ISSUE TITLE
Segfault Data folder

### ISSUE THREAD

**Issue by jferdelyi** [jferdelyi/Indexation#1]
Une segmentation fault apparait si on met un sous-dossier dans le dossier Data.

**Comment by Sub028** [comment]
A l'exécution de ton programme, lorsque tu lis les noms des fichiers dans le dossiers Data? Est-ce que tu prendrais pas le nom du dossier comme le nom d'un fichier?

**Comment by jferdelyi** [comment]
Si, mais dans l’immédiat je met ça comme un bug car on va pas gérer les sous-dossier.
En finalité il faudra que les dossier soit simplement pas pris en compte !
