### ISSUE TITLE
Bug detection de fichier supprimé !

### ISSUE THREAD

**Issue by jferdelyi** [jferdelyi/Indexation#2]
Dans une condition encore indéterminée, le système d'indexation plante ... 
Il précise qu'un fichier a été supprimé mais ne l’enlève pas de la base !

**Comment by Sub028** [comment]
Comment procèdes-tu pour delete ton fichier de la base? 
- Relecture de ta base et réécriture complète?
- Suppression de la partie correspondante?

**Comment by jferdelyi** [comment]
Alors je fait de la façon suivante : 
- J'ouvre (crée) un fichier tmp (un pour la liste des descripteurs et un pour la base audio)
- Je commence par la base des descripteurs, je copie tous sur le tmp sauf la ligne du descripteur a supprimer
- Pour la bases des descripteur je fait pareil, je copie tant que je suis pas au niveau de l'entête, je récupère le nombre de ligne, j'ignore le nombre de ligne donner, et je continue ma copie
- Je renomme les fichiers tmp
