### ISSUE TITLE
Bug pour commit et push!

### ISSUE THREAD

**Issue by Sub028** [jferdelyi/Indexation#4]
Je n'ai toujours pas réussi à faire un commit ... 
Procédure: 
git add "les fichiers"
git commit -s
git push origin master

Mais ça ne fonctionne pas ...

**Comment by jferdelyi** [comment]
Je vais utiliser ceci :
- git remote Aurelien https://github.com/Sub028/Indexation.git
- git pull Aurelien master
- git push origin master

**Comment by Sub028** [comment]
Bug fix thanks!
